12.0 voip jcs
odoo/documentation-user pull request #783
Opened 2020-11-06 17:22 UTC by jcs-odoo

2020-11-06 19:33 UTC, jcs-odoo commented on general.rst
> +   general/voip
For the forward port in ulterior version, this line can be put after **Payment Acquirers** and before **In-App Purchase**

2020-11-09 11:01 UTC, AntoineVDV approved these changes
> [MOV] general: moving VoIP docs from "CRM" to "general" 

Please only do that in >= 13.0
The structure in 12.0 is too much different from that of 13.0. That'd lead to overly complicated gitmnastic and content loss.

2020-11-09 11:01 UTC, AntoineVDV requested changes
Clicked the wrong radio ><

2020-11-12 14:07 UTC, jcs-odoo commented
Duplicate of #784 

which is based on 13.0

2020-11-12 14:07 UTC, closed without merging

2020-11-16 09:14 UTC, jcs-odoo commented
@AntoineVDV I guess we can delete the branch as well, then.