[ADD] sign: add a 1st doc for Sign on the validity of e-signatures
odoo/documentation-user pull request #805
Opened 2020-12-08 22:56 UTC by xpl-odoo

As requested by CJA: https://www.odoo.com/web#active_id=2227553&cids=1&id=2227553&model=project.task&menu_id=
(to be added first to 13.0 as per ANV's instructions)

2020-12-09 09:17 UTC, AntoineVDV reviewed
Hi @xpl-odoo, I updated the label since we use "new content request" for issues (issues and PRs share their labels).
Apart from that, the RST is neat :ok_hand: 
For the commit message, you could just go with "[ADD] sign: document the validity of e-signatures"

2020-12-21 12:54 UTC, jcs-odoo requested changes
Hi @xpl-odoo,

good job!

I just need a few small changes (if you agree with my suggestions) + renaming the commit as Antoine suggested above (this can be done when you do the `git commit --amend` command), then I'll approve it.

Cheers,

2020-12-21 12:54 UTC, jcs-odoo commented on sign/overview/signature_validity.rst
> +<https://europa.eu/european-union/about-eu/countries_en>`_
```suggestion
The `eIDAS regulation <http://data.europa.eu/eli/reg/2014/910/oj>`_ establishes the framework for
electronic signatures in all `27 member states of the European Union
<https://europa.eu/european-union/about-eu/countries_en>`_.
```

2020-12-21 12:54 UTC, jcs-odoo commented on sign/overview/signature_validity.rst
> +acts instead.
```suggestion
The `ESIGN Act (Electronic Signatures in Global and National Commerce Act)
<https://www.fdic.gov/regulations/compliance/manual/10/X-3.1.pdf>`_, at the interstate and
international levels, and the `UETA (Uniform Electronic Transactions Act)
<https://www.uniformlaws.org/committees/community-home/librarydocuments?communitykey=2c04b76c-2b7d-4399-977e-d5876ba7e034&tab=librarydocuments>`_,
at the state level, provide the legal framework for electronic signatures. Note that `Illinois
<https://www.ilga.gov/legislation/ilcs/ilcs5.asp?ActID=89&>`_ and `New York
<https://its.ny.gov/electronic-signatures-and-records-act-esra>`_ have not adopted the UETA, but similar
acts instead.
```

2020-12-21 12:54 UTC, jcs-odoo commented on sign/overview/signature_validity.rst
> +   that details how the signature was captured.
```suggestion
#. The signature must be associated with the document being signed, for example, by keeping a record
   detailing how the signature was captured.
```

2020-12-21 12:54 UTC, jcs-odoo commented on sign/overview/signature_validity.rst
> +   to download a copy.
```suggestion
#. Electronically signed documents need to be retained and available for later reference by all
   parties involved, for example, by providing the signer either a fully-executed copy or the option
   to download a copy.
```

2020-12-21 12:54 UTC, jcs-odoo commented on sign/overview/signature_validity.rst
> +   guarantee that the information is current. We advise you to should contact a local attorney to
```suggestion
   guarantee that the information is up to date. We advise you to should contact a local attorney to
```

2020-12-22 09:49 UTC, xpl-odoo commented
I have 'accepted' all your suggestions and renamed the commit accordingly.

2020-12-22 10:36 UTC, jcs-odoo approved these changes

2020-12-22 10:55 UTC, merged