[IMP] purchase: update and merge 3-way matching and bill control
odoo/documentation-user pull request #829
Opened 2021-01-11 09:38 UTC by xpl-odoo

3-way matching and bill control are closely related and were very shorts docs,
so in order to make more sense, both docs were merged. Both also had to be updated
for v14 since Odoo behaviour changed: when the bill control policy is set to
'on received quantities' you cannot create a bill anymore unless you have received
at least some products. Previously, you could create a bill for "0" and the "should
be paid' status was set to 'no'. Info about the "Bill status" field was also added
as it is also closely related.

2021-02-04 14:11 UTC, AntoineVDV requested changes
Missing blank line in the commit message, otherwise ok.

2021-02-04 20:51 UTC, xpl-odoo commented on purchase/advanced.rst
> -   advanced/3_way_matching
Yes indeed. Problem is, it should redirect to a folder (manage_deals) that was changed in another unmerged PR (823).
As instructed, you told me to work as if someone else did those changes and to rebase afterward 

> git checkout 14.0 / git pull / git checkout 14.0-purchase-control_bills-xpl / git rebase 14.0

and then I assume I need to 

> git add . / git commit --amend / git push --force-with-lease

Right? I might need to check the redirects at that stage though.

2021-02-05 08:47 UTC, AntoineVDV commented on purchase/advanced.rst
> -   advanced/3_way_matching
I don't think that you need to worry about redirections for folders (toctrees in sphinx) if you had no direct way for landing on them.

2021-02-05 09:06 UTC, AntoineVDV approved these changes

2021-02-05 10:59 UTC, merged