[ADD] Minor change - Webinars on top l10n_co
odoo/documentation-user pull request #835
Opened 2021-01-15 00:32 UTC by vbe-odoo

l10n_co (Colombia):

The change is due to a request to add webinars we had per localization to improve the visibility of this as a tool both for customers and Odooers. Why at the beginning? This is because is the first thing you see when accessing the documentation.

This is a minor change.

2021-01-15 16:08 UTC, jcs-odoo requested changes
see #832

2021-01-20 23:52 UTC, jcs-odoo commented
closes #833  
closes #834 
closes #836

2021-01-21 09:06 UTC, Lau-Odoo approved these changes

2021-01-21 09:07 UTC, jcs-odoo approved these changes

2021-01-21 09:08 UTC, merged