[REM] removed redundant customer portal portion
odoo/documentation-user pull request #909
Opened 2021-03-22 22:04 UTC by ksc-odoo

2021-03-23 08:40 UTC, Lau-Odoo approved these changes

2021-03-31 12:22 UTC, AntoineVDV requested changes
[REM] **ecommerce:** removed redundant customer portal portion

While you're at it, could you also take the opportunity to clean the empty lines at the end of `ecommerce/shopper_experience.rst`? There should only be one empty line left at line 9.

2021-04-01 13:08 UTC, jcs-odoo requested changes
@ksc-odoo @Lau-Odoo 

That is indeed quite a straightforward doc!
Could you please improve the commit message (and pull request's title along).
For example:
```
[REM] ecommerce: customer portal

+explanation
```
And see the point about the title.
I'll approve this pr after these two small changes :)

Cheers!

2021-04-01 13:08 UTC, jcs-odoo commented on ecommerce/shopper_experience.rst
> +Get Paid
If your commit is about removing [REM] a doc, then this change
- shouldn't be part of this commit
- could be put in another commit

Also, I don't think it's that important. (To clarify things about capitalization, I'll talk with Julien and see if we put it in the guidelines or not)

2021-04-01 13:18 UTC, jcs-odoo commented
@Lau-Odoo @ksc-odoo 
Sorry, I forgot again a point:

The images referenced in this doc are not deleted. They should be, if they arent' used in other docs.

2021-04-07 19:54 UTC, closed without merging